name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go get github.com/dsoprea/go-exif/v3
          go get github.com/dsoprea/go-jpeg-image-structure/v2
          go get golang.org/x/image/draw

      - name: Build
        run: |
          BINARY_NAME=snap-memory-downloader
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $BINARY_NAME main.go

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            snap-memory-downloader
            snap-memory-downloader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}