# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags: ['*']
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          go get github.com/dsoprea/go-exif/v3
          go get github.com/dsoprea/go-jpeg-image-structure/v2
          go get golang.org/x/image/draw

      - name: Build
        run: |
          BINARY_NAME=snap-memory-downloader
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $BINARY_NAME main.go

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            snap-memory-downloader
            snap-memory-downloader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}